<h1 align='center'>Модуль NumPy</h1>

## Основной объект - многомерный массив (ndarray)

### Одномерный массив

In [ ]:
# подключение модуля и сокращение названия для удобства
import numpy as np

np.set_printoptions(precision=3) # настройка вывода элементов массива не более 3 цифр после запятой

In [ ]:
# создание одномерного массива на основе списка
arr = np.array([1, 3, 6, 4, 7, 2, 9, 5, 8])

print('%25s'%'тип объекта:', type(arr))
print('%25s'%'тип элемента массива:', arr.dtype)
print('%25s'%'форма массива:', arr.shape)
print('%25s'%'содержимое массива:', arr)
arr


             тип объекта: <class 'numpy.ndarray'>
    тип элемента массива: int32
           форма массива: (9,)
      содержимое массива: [1 3 6 4 7 2 9 5 8]


array([1, 3, 6, 4, 7, 2, 9, 5, 8])

In [ ]:
# создание одномерного массива с заданием типа элемента

for dt in [np.int32, np.float64, np.bool]:
    arr = np.array([1, 3, 0, 4, 7, 0, 9, 5, 8], dtype=dt)
    print('%25s %s %s'%(dt, type(arr), arr))


    <class 'numpy.int32'> <class 'numpy.ndarray'> [1 3 0 4 7 0 9 5 8]
  <class 'numpy.float64'> <class 'numpy.ndarray'> [1. 3. 0. 4. 7. 0. 9. 5. 8.]
           <class 'bool'> <class 'numpy.ndarray'> [ True  True False  True  True False  True  True  True]


In [ ]:
# аналог range - создание последовательности с заданным шагом

arr = np.arange(0, 5, 0.5)
arr


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
# linspace - равномерное размещение заданного количества точек в отрезке

print('%25s'%'обычный linspace',       np.linspace(0, 10, 11))
print('%25s'%'с возвращением шага',    np.linspace(0, 10, 11, retstep=True))
print('%25s'%'не включая правый край', np.linspace(0, 10, 11, endpoint=False))


         обычный linspace [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
      с возвращением шага (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
   не включая правый край [0.    0.909 1.818 2.727 3.636 4.545 5.455 6.364 7.273 8.182 9.091]


In [ ]:
# срезы (slice) - это новые представления (view) массива

arr = np.arange(0, 5, 0.5)
arr[::2], arr[-3:]


(array([0., 1., 2., 3., 4.]), array([3.5, 4. , 4.5]))

In [ ]:
# изменение части массива при помощи среза
# задействован broadcasting - о нем далее

print(arr)
arr[::2] = 0
print(arr)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 0.  1.5 0.  2.5 0.  3.5 0.  4.5]


### Многомерный массив

In [ ]:
# создание двумерного массива на основе списка списков
arr = np.array([[1, 3, 6], [4, 7, 2], [9, 5, 8]])

print('shape', arr.shape)
arr


shape (3, 3)


array([[1, 3, 6],
       [4, 7, 2],
       [9, 5, 8]])

In [ ]:
# создание двумерного массива при помощи метода reshape
arr = np.arange(9).reshape(3, 3)

print('shape', arr.shape)
arr


shape (3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# транспонирование массива

print(arr.T)
print(np.transpose(arr))


[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
# срезы многомерного массива

print('arr\n', arr)
print('строка 2', arr[2, :])
print('столбец 1\n', arr[:, 1])
print('каждая вторая строка, столбцы 1,2\n', arr[::2, 1:3])


arr
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
строка 2 [6 7 8]
столбец 1
 [1 4 7]
каждая вторая строка, столбцы 1,2
 [[1 2]
 [7 8]]


### Broadcasting

<img src="numpy_broadcasting.png"></img>

In [ ]:
# механизм broadcasting
# большинство операций над массивами "приводят" их к максимальным размерам, если количество измерений совпадает

arr1 = np.array([0,1,2,3,4]).reshape(-1,1)*10
arr2 = np.array(range(5))

print('arr1:\n', arr1)
print('arr2:', arr2)

arr = arr1+arr2
arr


arr1:
 [[ 0]
 [10]
 [20]
 [30]
 [40]]
arr2: [0 1 2 3 4]


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### Полезные функции для создания массивов

In [ ]:
# пустой массив - не инициализирует значения элементов
np.empty((5,5))


array([[6.230e-307, 4.673e-307, 1.691e-306, 7.566e-307, 1.891e-307],
       [1.380e-306, 1.057e-307, 8.011e-307, 1.780e-306, 7.566e-307],
       [1.024e-306, 1.335e-306, 2.225e-306, 1.424e-306, 8.456e-307],
       [6.898e-307, 1.113e-306, 1.113e-306, 1.380e-306, 1.335e-306],
       [8.456e-307, 1.068e-306, 1.057e-307, 2.225e-306, 6.691e+164]])

In [ ]:
# массив из нулей
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# массив из единиц
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# единичная матрица
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# единичную диагональ задает параметр k
np.eye(5, k=-1)


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
# создать матрицу с заданной диагональю
np.diag([1,2,3], k=1)


array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
# достать заданную диагональ из матрицы
print(arr)
np.diag(arr, k=-1)


[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([10, 21, 32, 43])

### Генерация псевдослучайных последовательностей

In [ ]:
import numpy.random as npr
npr.seed(1234)

# равномерно распределенные случайные числа в полуинтервале [0, 1)
npr.rand(5, 5)


array([[0.192, 0.622, 0.438, 0.785, 0.78 ],
       [0.273, 0.276, 0.802, 0.958, 0.876],
       [0.358, 0.501, 0.683, 0.713, 0.37 ],
       [0.561, 0.503, 0.014, 0.773, 0.883],
       [0.365, 0.615, 0.075, 0.369, 0.933]])

In [ ]:
# нормально распределенные случайные числа с заданным средним и стандартным отклонением
npr.normal(10, 2, size=(5,5))


array([[ 7.747, 13.318,  8.679, 12.082, 12.106],
       [10.389, 12.717,  9.426, 10.883,  8.46 ],
       [ 8.051, 11.418,  9.788, 11.554, 11.828],
       [13.378,  8.817, 10.086,  6.208, 11.368],
       [ 7.987, 10.015, 12.462, 14.001,  8.656]])

In [ ]:
# выбрать псевдослучайный элемент из последовательности

for _ in range(20):
    print(npr.choice(list('последовательность')), end=' ')
    

т п с о ь в е в ь п т т о о л ь т н п е 

In [ ]:
# перемешать элементы изменяемой последовательности
lst = list(range(20))
print('initial list', lst)
npr.shuffle(lst)
print('shuffled list', lst)


initial list [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
shuffled list [19, 5, 10, 6, 15, 16, 3, 7, 13, 11, 18, 2, 14, 9, 17, 1, 12, 8, 0, 4]


### Поэлементные операции над массивами

In [ ]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)

print('             сложение:', arr1+arr2)
print('            умножение:', arr1*arr2)
print('  умножение на скаляр:', arr1*5)
print(' возведение в степень:', arr1**2)
print('            сравнение:', arr1<arr2)
print('целочисленное деление:', arr1//3)
print('   остаток от деления:', arr1%3)


             сложение: [10 12 14 16 18]
            умножение: [ 0 11 24 39 56]
  умножение на скаляр: [ 0  5 10 15 20]
 возведение в степень: [ 0  1  4  9 16]
            сравнение: [ True  True  True  True  True]
целочисленное деление: [0 0 0 1 1]
   остаток от деления: [0 1 2 0 1]


### Простая обработка массивов

In [ ]:
# поиск минимума, максимума, среднего, стандартного отклонения
arr = npr.rand(10)

print(' arr:', arr)
print(' min:', np.min(arr))
print(' max:', np.max(arr))
print('mean:', np.mean(arr))
print(' std:', np.std(arr))


 arr: [0.782 0.267 0.214 0.178 0.429 0.972 0.047 0.917 0.159 0.943]
 min: 0.04653157887508852
 max: 0.972113122851516
mean: 0.49083275051822584
 std: 0.3520120620971702


In [ ]:
# поиск минимума, максимума, среднего, стандартного отклонения вдоль заданного измерения

arr = npr.rand(5, 5)

print(' arr:\n', arr)
print(' min:', np.min(arr, axis=0))
print(' max:', np.max(arr, axis=0))
print('mean:', np.mean(arr, axis=0))
print(' std:', np.std(arr, axis=0))


 arr:
 [[0.763 0.054 0.254 0.928 0.838]
 [0.157 0.691 0.367 0.937 0.613]
 [0.699 0.503 0.711 0.134 0.829]
 [0.743 0.457 0.079 0.373 0.934]
 [0.419 0.234 0.572 0.572 0.417]]
 min: [0.157 0.054 0.079 0.134 0.417]
 max: [0.763 0.691 0.711 0.937 0.934]
mean: [0.556 0.388 0.397 0.589 0.726]
 std: [0.235 0.221 0.224 0.313 0.187]


In [ ]:
# поиск индексов минимального, максимального, ненулевого элементов или по условию
arr = npr.rand(5, 5)
arr[arr<0.5] = 0

print('arr:\n', arr)
print('argmin:', np.argmin(arr))
print('argmax:', np.argmax(arr))
print('argwhere:\n', np.argwhere(arr<0.3))


arr:
 [[0.626 0.    0.622 0.    0.974]
 [0.773 0.    0.    0.    0.   ]
 [0.    0.658 0.566 0.569 0.654]
 [0.    0.952 0.    0.85  0.96 ]
 [0.    0.    0.    0.665 0.   ]]
argmin: 1
argmax: 4
argwhere:
 [[0 1]
 [0 3]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [3 0]
 [3 2]
 [4 0]
 [4 1]
 [4 2]
 [4 4]]


### Специальная индексация и маскирование (fancy indexing and masking)

In [ ]:
arr = np.arange(10)[::-1]
print(arr)

arr[[1,1,1]] # получить представление части массива, заданной индексами 1,5,7


[9 8 7 6 5 4 3 2 1 0]


array([8, 8, 8])

In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)

idx = [1,2,3]
arr[idx, idx] # получить диагональные элементы с индексами (1,1),(2,2),(3,3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 5, 10, 15])

In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)

idx = np.array([[1,2,3]])
arr[idx.T, idx] # получить подматрицу на пересечении столбцов и строк с индексами 1,2,3


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
idx = [1,2,3]

print(np.ix_(idx, idx)) # создает "открытую решетку" из индексов
arr[np.ix_(idx, idx)]


(array([[1],
       [2],
       [3]]), array([[1, 2, 3]]))


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
arr = npr.rand(10)

mask = arr < 0.5 # создание маски

print('   arr:', arr)
print('  mask:', mask)
print('result:', arr[mask])

   arr: [0.377 0.014 0.339 0.401 0.468 0.652 0.997 0.517 0.404 0.058]
  mask: [ True  True  True  True  True False False False  True  True]
result: [0.377 0.014 0.339 0.401 0.468 0.404 0.058]


In [ ]:
arr = npr.rand(5, 5)

mask = arr < 0.5 # создание маски

print('arr:\n', arr)
print('mask:\n', mask)
print('result:\n', arr[mask])

arr:
 [[0.045 0.627 0.008 0.418 0.006]
 [0.424 0.363 0.619 0.419 0.014]
 [0.413 0.22  0.53  0.78  0.522]
 [0.505 0.065 0.408 0.703 0.924]
 [0.55  0.332 0.643 0.952 0.214]]
mask:
 [[ True False  True  True  True]
 [ True  True False  True  True]
 [ True  True False False False]
 [False  True  True False False]
 [False  True False False  True]]
result:
 [0.045 0.008 0.418 0.006 0.424 0.363 0.419 0.014 0.413 0.22  0.065 0.408
 0.332 0.214]


### Склеивание, поворот, отражение и др.

In [ ]:
# склеить массивы горизонтально
arr = np.arange(5)

print('   arr:', arr)

np.hstack((arr, arr))


   arr: [0 1 2 3 4]


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [ ]:
# склеить массивы горизонтально
arr = np.arange(5).reshape(-1,1)

print('   arr:\n', arr)

np.hstack((arr, arr))


   arr:
 [[0]
 [1]
 [2]
 [3]
 [4]]


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
# склеить массивы вертикально
arr = np.arange(5)

print('   arr:', arr)

np.vstack((arr, arr))


   arr: [0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# склеить массивы вертикально
arr = np.arange(5).reshape(-1,1)

print('   arr:\n', arr)
np.vstack((arr, arr))


   arr:
 [[0]
 [1]
 [2]
 [3]
 [4]]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# сложить две матрицы в трехмерный массив
arr = np.arange(9).reshape(3,3)

stack = np.stack((arr, arr), axis=2)
print(stack.shape)
stack


(3, 3, 2)


array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]],

       [[6, 6],
        [7, 7],
        [8, 8]]])

In [ ]:
# циклический сдвиг вдоль измерения
arr = np.arange(9).reshape(3,3)
print('arr:', arr)

np.roll(arr, 1, axis=1)


arr: [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [ ]:
# отражение верх-низ
np.flipud(arr)


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
# отражение лево-право
np.fliplr(arr)


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
# поворот массива на 90, 180, 270 градусов по/против часовой стрелки
arr = np.zeros((5,5))

for i in range(4):
    arr[0, :-1] = range(i*4, (i+1)*4)
    arr = np.rot90(arr, 1)

for i in range(4):
    print(i, '\n', arr)
    arr = np.rot90(arr, 1)


0 
 [[ 0.  1.  2.  3.  4.]
 [15.  0.  0.  0.  5.]
 [14.  0.  0.  0.  6.]
 [13.  0.  0.  0.  7.]
 [12. 11. 10.  9.  8.]]
1 
 [[ 4.  5.  6.  7.  8.]
 [ 3.  0.  0.  0.  9.]
 [ 2.  0.  0.  0. 10.]
 [ 1.  0.  0.  0. 11.]
 [ 0. 15. 14. 13. 12.]]
2 
 [[ 8.  9. 10. 11. 12.]
 [ 7.  0.  0.  0. 13.]
 [ 6.  0.  0.  0. 14.]
 [ 5.  0.  0.  0. 15.]
 [ 4.  3.  2.  1.  0.]]
3 
 [[12. 13. 14. 15.  0.]
 [11.  0.  0.  0.  1.]
 [10.  0.  0.  0.  2.]
 [ 9.  0.  0.  0.  3.]
 [ 8.  7.  6.  5.  4.]]


In [ ]:
arr[:2,:2]

array([[ 0.,  1.],
       [15.,  0.]])

In [ ]:
# повтор каждого элемента матрицы по 3 раза с увеличением количества столбцов
np.repeat(arr[:2,:2], 3, axis=1)

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [15., 15., 15.,  0.,  0.,  0.]])

In [ ]:
# повтор матрицы как единого блока по обеим измерениям
np.tile(arr[:2,:2], (3,2))

array([[ 0.,  1.,  0.,  1.],
       [15.,  0., 15.,  0.],
       [ 0.,  1.,  0.,  1.],
       [15.,  0., 15.,  0.],
       [ 0.,  1.,  0.,  1.],
       [15.,  0., 15.,  0.]])

### Линейная алгебра

In [ ]:
# норма вектора
np.linalg.norm([3,4])

5.0

In [ ]:
alpha = np.radians(30)
s, c = np.sin(alpha), np.cos(alpha)
arr = np.array([[c, s], [-s, c]])

np.linalg.eig(arr) # собственные числа и собственные векторы

(array([0.866+0.5j, 0.866-0.5j]), array([[0.707+0.j   , 0.707-0.j   ],
        [0.   +0.707j, 0.   -0.707j]]))

In [ ]:
# решить систему линейных уравнений

K = np.eye(3)
K[2,1]=2.
F = np.array([0, 1, 3])

print('solve: K*U=F')
print('K\n', K)
print('F', F)
print('U', np.linalg.solve(K, F))


solve: K*U=F
K
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
F [0 1 3]
U [0. 1. 1.]


In [ ]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)

# скалярное произведение
print(arr1.dot(arr2))
print(arr1@arr2)
print(np.dot(arr1, arr2))


130
130
130


In [ ]:
arr1 = np.arange(16).reshape(4,4)
arr2 = np.eye(4)*2

# матричное умножение
print(arr1.dot(arr2))
print(arr1@arr2)
print(np.dot(arr1, arr2))


[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]


## Сохранение и загрузка массивов

In [ ]:
N = 10
arr = np.arange(N*N).reshape(N, N)

np.save('arr.npy', arr) # сохранить массив в бинарном формате

np.load('arr.npy') # загрузить массив обратно


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
N = 10
arr = np.arange(N*N).reshape(N, N)

# сохранить массив в текстовом формате
np.savetxt('arr.txt', arr, fmt='%d', header ='Numpy array | Lecture 2 | PythonCourse', encoding='utf-8')

np.loadtxt('arr.txt', dtype=np.int32)#, usecols=(0,2,4)) # загрузить массив обратно


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#%load arr.txt


## Дополнения


[Scientific Python Lectures](https://github.com/jrjohansson/scientific-python-lectures)